#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  newline = true
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'p:green'
    template = ' {{ path .Path .Location }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:greyblue'
    template = """\
    {{ if .HEAD }}\
      {{ .HEAD }}\
      {{if or .Working.Changed .Staging.Changed }}{{ end }} \
      {{ if gt .Ahead 0 }}{{ .Ahead }} {{ end }}{{ if gt .Behind 0 }}{{ .Behind }} {{ end }}\
      (󰳏 {{ if .UpstreamURL }}{{ url .RepoName .UpstreamURL }}{{ else }}󰼈{{ end }}) \
    {{ else }}\
      (󰳏 󰼈) \
    {{ end }}\
    """

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true
      branch_icon = ""
      branch_identical_icon = ""
      branch_ahead_icon = "󱞾"
      branch_behind_icon = "󱞤"
      branch_gone_icon = "󰼈"
      ignore_status = [
        "qmk_firmware"
      ]
  
[[blocks.segments]]
    type = 'go'
    style = 'plain'
    foreground = 'p:cyan'
    background = 'transparent'
    template = " "

  [[blocks.segments]]
    type = 'dotnet'
    style = 'plain'
    foreground = 'p:purple'
    background = 'transparent'
    template = "󰪮 "

  [[blocks.segments]]
    type = 'rust'
    style = 'plain'
    foreground = 'p:orange'
    background = 'transparent'
    template = "󱘗 "

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = ' '

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false
      fetch_virtual_env = false

[[blocks]]
  type = 'prompt'
  newline = true
  alignment = "left"

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = 'p:red'
    template = '󱦛'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{ if .Root }}p:red{{ else }}p:pink{{ end }}"
    ]
    background = 'transparent'
    template = '{{ if .Root }}${{ else }}❯{{ end }}'

[[tooltips]]
  type = 'owm'
  tips = ['owm',
  'weather',
  'temp']
  style = 'plain'
  foreground = 'p:orange'
  background = 'transparent'
  leading_diamond = ''
  trailing_diamond = ''
  template = ' {{.Weather}} ({{.Temperature}}{{.UnitIcon}}) '

  [tooltips.properties]
    location = "Madison,WI,US"
    units = 'imperial'
    http_timeout = 500
    cache_timeout = 10

[[tooltips]]
  type = 'time'
  tips = ['date', 'time']
  style = 'plain'
  foreground = 'p:red'
  template = ' {{ .CurrentDate | date .Format }} '

  [tooltips.properties]
    time_format = "Jan 2, 06 - 03:04 PM"

[transient_prompt]
  foreground = 'p:black'
  background = 'transparent'
  template = '<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></> '

[secondary_prompt]
  foreground = 'p:black'
  background = 'transparent'
  template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '

[palette]
  black = '#262B44'
  cyan = '#8BE9FD'
  green = '#50FA7B'
  orange = '#FFB86C'
  red = '#FF5555'
  white = '#F8F8F2'
  yellow = '#F1FA8C'
  purple = '#BD93F9'
  pink = '#FF79C6'
  greyblue = "#6272A4"
